#ifndef H_PUNKNOBS_WIN
#define H_PUNKNOBS_WIN

#include "punknobs.h"

// # DirectInput codes
enum punknobs_directinput_type
{
	PUNKNOBS_DIRECTINPUT_TYPE_AXIS,
	PUNKNOBS_DIRECTINPUT_TYPE_SLIDER,
	PUNKNOBS_DIRECTINPUT_TYPE_HAT,
	PUNKNOBS_DIRECTINPUT_TYPE_BUTTON,
};

enum punknobs_directinput_code
{
	PUNKNOBS_DIRECTINPUT_CODE_X,
	PUNKNOBS_DIRECTINPUT_CODE_Y,
	PUNKNOBS_DIRECTINPUT_CODE_Z,
	PUNKNOBS_DIRECTINPUT_CODE_RX,
	PUNKNOBS_DIRECTINPUT_CODE_RY,
	PUNKNOBS_DIRECTINPUT_CODE_RZ,
	PUNKNOBS_DIRECTINPUT_CODE_SLIDER_1,
	PUNKNOBS_DIRECTINPUT_CODE_SLIDER_2,
	PUNKNOBS_DIRECTINPUT_CODE_HAT_1,
	PUNKNOBS_DIRECTINPUT_CODE_HAT_2,
	PUNKNOBS_DIRECTINPUT_CODE_HAT_3,
	PUNKNOBS_DIRECTINPUT_CODE_HAT_4,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_1,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_2,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_3,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_4,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_5,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_6,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_7,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_8,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_9,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_10,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_11,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_12,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_13,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_14,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_15,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_16,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_17,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_18,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_19,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_20,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_21,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_22,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_23,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_24,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_25,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_26,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_27,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_28,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_29,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_30,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_31,
	PUNKNOBS_DIRECTINPUT_CODE_BUTTON_32,
};

// # Xinput codes
enum punknobs_xinput_type
{
	PUNKNOBS_XINPUT_TYPE_AXIS,
	PUNKNOBS_XINPUT_TYPE_BUTTON,
};

enum punknobs_xinput_code
{
	PUNKNOBS_XINPUT_CODE_BUTTON_DPAD_UP,
	PUNKNOBS_XINPUT_CODE_BUTTON_DPAD_DOWN,
	PUNKNOBS_XINPUT_CODE_BUTTON_DPAD_LEFT,
	PUNKNOBS_XINPUT_CODE_BUTTON_DPAD_RIGHT,
	PUNKNOBS_XINPUT_CODE_BUTTON_START,
	PUNKNOBS_XINPUT_CODE_BUTTON_BACK,
	PUNKNOBS_XINPUT_CODE_BUTTON_STICK_LEFT,
	PUNKNOBS_XINPUT_CODE_BUTTON_STICK_RIGHT,
	PUNKNOBS_XINPUT_CODE_BUTTON_SHOULDER_LEFT,
	PUNKNOBS_XINPUT_CODE_BUTTON_SHOULDER_RIGHT,
	PUNKNOBS_XINPUT_CODE_BUTTON_A,
	PUNKNOBS_XINPUT_CODE_BUTTON_B,
	PUNKNOBS_XINPUT_CODE_BUTTON_X,
	PUNKNOBS_XINPUT_CODE_BUTTON_Y,
	PUNKNOBS_XINPUT_CODE_AXIS_STICK_LEFT_VERTICAL,
	PUNKNOBS_XINPUT_CODE_AXIS_STICK_LEFT_HORIZONTAL,
	PUNKNOBS_XINPUT_CODE_AXIS_STICK_RIGHT_VERTICAL,
	PUNKNOBS_XINPUT_CODE_AXIS_STICK_RIGHT_HORIZONTAL,
	PUNKNOBS_XINPUT_CODE_AXIS_TRIGGER_LEFT,
	PUNKNOBS_XINPUT_CODE_AXIS_TRIGGER_RIGHT,
};

enum punknobs_xinput_value
{
	PUNKNOBS_XINPUT_VALUE_BUTTON_RELEASED,
	PUNKNOBS_XINPUT_VALUE_BUTTON_PRESSED,
};

enum punknobs_win_api
{
	PUNKNOBS_WIN_API_DIRECTINPUT = 0,
	PUNKNOBS_WIN_API_XINPUT,
	PUNKNOBS_WIN_API_COUNT,
};

// # Regular Punknobs stuff
struct punknobs_win_delays
{
	unsigned delay_device_refresh;
	unsigned delay_input_refresh;
};

void punknobs_prepare_init_win(
	struct punknobs_config_backend* config,
	struct punknobs_error_info* error);

void punknobs_win_set_delays(
	struct punknobs* context,
	struct punknobs_win_delays* delays,
	struct punknobs_error_info* error);

void punknobs_win_set_window(
	struct punknobs* context,
	void* window);

enum punknobs_win_api punknobs_win_device_get_api(
	struct punknobs* context,
	void* device_info,
	struct punknobs_error_info* error);

enum punknobs_win_api punknobs_win_input_get_api(
	struct punknobs* context,
	void* input_info,
	struct punknobs_error_info* error);

#endif
